### ISSUE TITLE
eurec4a_2019* trajectory examples are inconsistent

### ISSUE THREAD

**Issue by leifdenby** [EUREC4A-UK/lagtraj#106]
The dates in the input definition files with 2019 in the filename are inconsistent with the date range inside the files. We should decide what to do with these

Once this has been decided https://github.com/EUREC4A-UK/lagtraj/pull/103 needs redoing to reflect this

**Comment by sjboeing** [comment]
A quick suggestion here would be to include examples from the EUREC4A field campaign (Feb 2 and 5) and Cardington only with Lagtraj at this point.

**Comment by leifdenby** [comment]
TODO

- [ ] add "cardington" domain yaml-file
- [ ] add eulerian trajectory using "cardington" domain yaml-file
- [ ] add "cardington" forcing yaml-file
- [ ] remove `eurec4a_20191209_12_eul.yaml`
- [ ] remove `eurec4a_20191209_12_lag.yaml`
- [ ] remove `eurec4a_20191209_12_lin.yaml`
- [ ] change `eurec4a_20200202_12_lag_short_pressure.yaml` to be on the 5/2/2020T15Z, name will be `eurec4a_20200205_15_lag_short_pressure.yaml`, this should be version `1.0.0`
- [ ] change `eurec4a_20200202_12_lag_short.yaml` to be on the 5/2/2020T15Z, name will be `eurec4a_20200205_15_lag_short.yaml`, this should be version `1.0.0`
- keep `eurec4a_20200202_12_lag.yaml`
- keep `eurec4a_20200205_15_lag.yaml`
- keep `eurec4a_campaign_eulerian.yaml`
- [ ] add `eurec4a_20200205_15_lin.yaml`
- [ ] add `eurec4a_20200205_15_eul.yaml`
- [ ] change `TEST_FORCING_NAME = "lagtraj://eurec4a_20200205_15_lag"`

The Cardington yaml-file can be added without changes for over land being included in repo, only the values will be invalid.

**Comment by leifdenby** [comment]
@sjboeing I'm closing this since I think we have all the examples we want now and with https://github.com/EUREC4A-UK/lagtraj/pull/143 we also know that all examples in the README are valid and working
