### ISSUE TITLE
Add flag to allow downloading of grib data from CDS

### ISSUE THREAD

**Issue by leifdenby** [EUREC4A-UK/lagtraj#11]

**Comment by leifdenby** [comment]
Is this still relevant @sjboeing? I remember talking about it, but I'm not sure that it's worth our time

**Comment by sjboeing** [comment]
Let's close it for now. It is probably something we would like to add eventually, but for now we can manage with the present domain size which does not require cfgrib (I am having some trouble with trajectories from higher levels at the moment).
