### ISSUE TITLE
Unversioned domain data

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#110]
@leifdenby The version management is catching inconsistencies, though I haven't been able to quickly hack it to get the forcings routine to use the unversioned domain data I previously downloaded (an error occurs in line 76 of lagtraj/trajectory/load.py). I may just add a version attribute to the existing forcings as a hack, the question is whether we want to be able to use unversioned domains in the long run.

**Comment by leifdenby** [comment]
Ok, yes I haven't really written any documentation for this but, so let's talk about it on our next call :)

**Comment by leifdenby** [comment]
If you want a hand with this before we talk maybe you could paste in to a comment the commands you're running and the output?

**Comment by sjboeing** [comment]
I am having trouble reproducing this right now. Will let you know in case I find it again.

**Comment by sjboeing** [comment]
Closing this for now.
