### ISSUE TITLE
Conversion format parser argument

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#111]
I am having trouble with the parser argument for the conversion format in lagtraj/forcings/create.py. The code includes a --target-model argument, but also a conversion_name argument. The argument in the current README seems to be --convert.       
      main(
            data_path=args.data_path,
            forcing_defn=forcing_defn,
            conversion_name=args.conversion_name,
        )
We may want to also allow for this argument to be absent.

**Comment by leifdenby** [comment]
Ok, yes let's have a chat about this

**Comment by sjboeing** [comment]
@leifdenby: I just checked with a clean version of lagtraj. The same issue seems to appear in that case. This may not be picked up by unit tests.

**Comment by leifdenby** [comment]
Ah, yes. I see what you mean. Lines https://github.com/EUREC4A-UK/lagtraj/blob/master/lagtraj/forcings/create.py#L224 and https://github.com/EUREC4A-UK/lagtraj/blob/master/lagtraj/forcings/create.py#L240 are inconsistent. I changed my mind about what to name these. I thought `target_name` was good at first, but eventually changed my mind to call it `conversion` (more in line with what you'd done before). Unfortunately none of the tests test the command line interfaces (CLIs) at the moment. But I'll quickly code up some tests to refactor that argparser routines and add some tests.

**Comment by leifdenby** [comment]
This should be fixed now I merged in that pull-request. When you give it a try @sjboeing could you close the issue if it works now? Cheers

**Comment by sjboeing** [comment]
Thanks, Leif. This now works well!
