### ISSUE TITLE
Lagtraj - suggestions for documentation

### ISSUE THREAD

**Issue by ralphburton** [EUREC4A-UK/lagtraj#126]
Hi Leif and Steef,

Thank you very much for this.

I've gone through this from beginning to end and have managed to create a dephy netcdf file. Great!

Just a few comments on the documentation:

In the block of code just after the para. "You can either make your own..." there is "lagraj" ......--> "lagtraj"...maybe needs correcting for lazy people like me who copy-and-paste.

Likewise, throughout, code refers to "lagtraj.forcing.create" etc. when it should be "lagtraj.forcings.create" I think.

Might be worth mentioning that in "Making Source Data Available" that the user needs an account with cds.climate.copernicus.eu and also needs a .cdsapirc file in their home directory containing their User ID and API key etc.

A couple of other things:

When I did the conversion to dephy, the netcdf files were placed in data/forcings, but the eurec4a_20191209_12_lag.dephy.yaml was placed in a new directory data/forcings/lagtraj:   (n.b. the colon in the directory name) -- is this intentional?

Also, Steef, I told you I had had some problems downloading data: the ERA5 data showed as queued on copernicus, and was in the queue for 8 hours: I haven't had this again. I didn't need to use the retry-rate option. Hopefully that was just a blip.

Cheers both of you, a very nice piece of work! 

Ralph

**Comment by sjboeing** [comment]
Thanks @ralphburton. I don't think the colon in the directory name is intentional. I will look into these in more detail later this week.

**Comment by leifdenby** [comment]
thanks @ralphburton! I'll break this down into a TODO list below

- [ ] fix typo in README in the block of code just after the paragraph `You can either make your own...`: `lagraj` --> `lagtraj`
- [ ] fix typos in README: `lagtraj.forcing.create` -> `lagtraj.forcings.create`
- [ ] add details to README on obtaining an account from cds.climate.copernicus.eu (and creating `~/.cdsapirc`) for download ERA5 data
- [ ] fix bug in path for converted forcing files, currently yaml-file for converted forcing is placed in `data/forcings/lagtraj:` for `eurec4a_20191209_12_lag.dephy.yaml`. netcdf files were placed in `data/forcings`

> Also, Steef, I told you I had had some problems downloading data: the ERA5 data showed as queued on copernicus, and was in the queue for 8 hours: I haven't had this again. I didn't need to use the retry-rate option. Hopefully that was just a blip.

Depending on the amount of data you're requesting it can often take hours @ralphburton. You should give the retry-rate flag a try, that way you can ensure you get your data eventually :)

**Comment by leifdenby** [comment]
@sjboeing in pull-request #127 above I have added a test which reads the README file and finds all lagtraj commands and tries to run them. You can see from the output log of the run that that it fails on some of the commands in the README, this is because of the issue of the conversion with lagtraj bundled conversions having in a bug in how the yaml-file path was constructed, but I am fixed that in #128.
