### ISSUE TITLE
Issues downloading on JASMIN

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#131]
More details to follow. Lagtraj seems to get stuck after downloading 1 file.

**Comment by sjboeing** [comment]
@leifdenby: unfortunately ctrl-C does not respond.
Last visible info:
Downloading files which are ready...
2021-07-06 20:40:33,151 INFO Downloading https://download-0011.copernicus-climate.eu/cache-compute-0011/cache/data0/adaptor.mars.external-1625568871.3732188-10068-8-d922e602-53d1-443c-a74b-ced77b0c7e34.nc to /gws/nopw/j04/eurec4auk/users/sboeing/lagtraj/data/domains/eurec4a_north_atlantic_data/an_model_2020-01-28.nc (9.1G)
2021-07-06 20:44:37,528 INFO Download rate 38.2M/s 

Opening with gdb says:
0x00007f49122066fd in write () from /lib64/libpthread.so.0
Missing separate debuginfos, use: debuginfo-install glibc-2.17-324.el7_9.x86_64

**Comment by sjboeing** [comment]
Do you know if any good python debug tools are available on JASMIN?

**Comment by sjboeing** [comment]
@leifdenby: I am making some progress here by manual debugging, it seems to be an issue in the fingerprinting and not JASMIN-specific (see-gw-01 has the same issues).

**Comment by sjboeing** [comment]
@leifdenby: the problem is with adding attributes on the netCDF file. It is strange I did not have problems with this before. It seems to work OK with xarray but I think I am writing the file again from scratch! More to follow.

**Comment by sjboeing** [comment]
@leifdenby:

Locally, I have replaced the fingerprinting with:
```python3
def _fingerprint_downloaded_file(query_hash, file_path):
    ds=xr.open_dataset(file_path)
    ds.attrs["dict_checksum"]=query_hash
    ds.to_netcdf(file_path)
```
 This ensures it does not get suck, but there may be more elegant solutions. What do you think?

**Comment by leifdenby** [comment]
Well done for finding this issue and fixing it!

**Comment by sjboeing** [comment]
Solving via #132

**Comment by sjboeing** [comment]
@leifdenby: Using xarray ruined the data. I now tried setncattr_string, which leads to an error:
  File "netCDF4/_netCDF4.pyx", line 2897, in netCDF4._netCDF4.Dataset.setncattr_string
OSError: file format does not support NC_STRING attributes
I will first try upgrading the netcdf4 package. Maybe an alternative would be to use a number as a hash?

**Comment by sjboeing** [comment]
Hi @leifdenby: I have meanwhile tried a few other things (numerical hashes, adding a variable instead). Nothing seems to work well on JASMIN at the moment with the default setup. I could try creating a clean conda environment, but maybe the better way would indeed be to store the hash separately at this point in the pipeline. Maybe we can build in some check to ensure the hash and the file are consistent when we load the file. Would you like to have a go at this?

**Comment by leifdenby** [comment]
@sjboeing I'm ready to have a try at fixing this. Could you give the command you're using and the branch of lagtraj you're working from please?

I assume the command is something like:

```bash
$> python -m lagtraj.domain.download ...
```
?

**Comment by sjboeing** [comment]
python -m lagtraj.domain.download lagtraj://eurec4a_north_atlantic 2020/01/28 2020/02/09

The branch is the recent EUREC4A-UK master branch. I am not sure if the problem is specific to either the larger domain or jasmin. The code works fine for small domains on my laptop.

**Comment by leifdenby** [comment]
@sjboeing I've had a go a removing the finger-printing in the pull-request above. I've currently got a download queued with the command you used. I'll let you know how it goes 😄

**Comment by sjboeing** [comment]
thanks @leifdenby. I see you have a few more pull requests open as well: just let me know if I can have a look at these as well.

**Comment by leifdenby** [comment]
With the finger printing removed we should be able to close this I think. Is that ok @sjboeing ?

**Comment by leifdenby** [comment]
I'm closing this @sjboeing. Please reopen if you experience the issue again
