### ISSUE TITLE
Remove redundant mask calculation

### ISSUE THREAD

**Issue by leifdenby** [EUREC4A-UK/lagtraj#137]
In discussion on https://github.com/EUREC4A-UK/lagtraj/pull/125#discussion_r648107923 @sjboeing and I noticed that currently the code expects there always to be a mask even when none is needed. This could be cleaned up to make the code clearer.

**Comment by sjboeing** [comment]
Would be nice to do this. Not giving this priority, but hope to revisit this later.

**Comment by sjboeing** [comment]
Is this a duplicate of #130?

**Comment by leifdenby** [comment]
> Is this a duplicate of #130?

yes, sorry, you're right. I'll close this
