### ISSUE TITLE
suggestion: install and use numba by default

### ISSUE THREAD

**Issue by leifdenby** [EUREC4A-UK/lagtraj#162]
@sjboeing I just installed lagtraj on a new computer I am developing on, and I noticed the tests were running very slowly. I then realise that this is because we don't install and use `numba` by default. I think we should change this as people are unlikely to realise that they should install numba otherwise. The only reasons I can see for not doing this are either 1) numba is hard to install or 2) numba isn't supported on all platforms we want to target. I don't think either of these are true:

1. numba can be installed with pip, conda isn't required
2. I can't see a platform missing from numba's list of supported platforms: https://numba.pydata.org/numba-doc/latest/user/installing.html

What do you think?

**Comment by sjboeing** [comment]
Yes, I think by now numba is only a minor additional dependency. It would be good to keep the option of running without numba optional (but maybe the user should need to very explicitly request it), as it can be useful for debugging.

**Comment by leifdenby** [comment]
https://github.com/EUREC4A-UK/lagtraj/pull/167 is ready for review now @sjboeing when you've got a moment to have a look :)

**Comment by sjboeing** [comment]
Closing via #167
