### ISSUE TITLE
Ensure tar ball with tests is up to date

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#166]
@leifdenby I am currently getting a substantial number of errors when trying to run the tests from the tar ball (maybe I just need to set another environment variable, or maybe this has become outdated?). The output is given below for reference.

[errors_with_tempdir.txt](https://github.com/EUREC4A-UK/lagtraj/files/9490119/errors_with_tempdir.txt)

**Comment by leifdenby** [comment]
Could you point me to the branch that you're working from and I will have a look?

**Comment by sjboeing** [comment]
It is the timings on master branch (https://github.com/EUREC4A-UK/lagtraj/pull/164)

**Comment by leifdenby** [comment]
Need to update dev notes to point to correct test data URL

https://github.com/EUREC4A-UK/lagtraj/blob/master/docs/developing.md
