### ISSUE TITLE
Ensure input-definition examples are extracted when installing from pypi

### ISSUE THREAD

**Issue by leifdenby** [EUREC4A-UK/lagtraj#177]
So, the good news is `v0.1.0` is now live on pypi (https://pypi.org/project/lagtraj/) @sjboeing :)

The bad news is that for some reason the input definition examples aren't being copied to the right place when installing from pypi. So when trying to list the included examples I get the following:

```
(lagtraj)  ✝  python3.8/site-packages/lagtraj  python -m lagtraj.input_definitions.examples                              
The following domain/forcing/trajectory definitions are currently included with lagtraj:

lagtraj://


To use for example the `eurec4a_north_atlantic` domain definition
for downloading domain data run lagtraj.domain.download as follows:

    $> python -m lagtraj.domain.download lagtraj://eurec4a_20200202_first
```

This is obviously needs fixing asap, and I'll then release `v0.1.0`.

**Comment by sjboeing** [comment]
Thanks for putting this on pypi, @leifdenby. Let me know if there is anything I can check.
