### ISSUE TITLE
a few comments on the read-me

### ISSUE THREAD

**Issue by ralphburton** [EUREC4A-UK/lagtraj#193]
Just some general comments that occurred to me as I was working through the instructions. All minor!

* Is it worth saying that download times may vary - I have submitted a download and it took 25 minutes. I tried again immediately afterwards (after removing the reanalysis files) and it took 30 s. I know this is at the mercy of the copernicus servers but might be worth a sentence to warn folks. Is there a "all files downloaded" message? I think there is but only when using the --retry-rate option?
* Mention that users need a copernicus account?
* Might be worth mentioning that you need the cds api installed (https://cds.climate.copernicus.eu/api-how-to)
* Also that users can monitor the status of the request via their cds.climate.copernicus.eu request page
* Is there a typo: "the <start_date> and <end_date> should be formatted as YYYY/MM/DD, e.g. 2020/02/01 for the 2nd of February 2020." ...should it be "e.g. 2020/02/02"

Other than that all good! Great work Leif and Steef. A very nice piece of work.

Cheers
Ralph

**Comment by sjboeing** [comment]
Thanks @ralphburton: I will have a go at this.

**Comment by sjboeing** [comment]
@ralphburton: I have made these changes in PR #194 and will now close the comment. In a download I did yesterday, I got an "all files downloaded" message also without the "--retry-rate" option, but let us  know if this is ever not the case and we can try to reproduce it.
