### ISSUE TITLE
Cancelled copernicus requests

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#20]
@leifdenby: I have added some more fields to the download, in order to get everything we need for the RACMO-formatted inputs. I noticed that when a request is cancelled on copernicus, but stays in the yaml list of requests, it is then no longer possible to try downloading again. Removing the lists of requests solves this, but there may be a better solution.

**Comment by leifdenby** [comment]
Could you show me where on copernicus I should go to cancel a request? I'll have a go at working out how to handle the API response from cdsapi where a request has been deleted. Thank you 😄

**Comment by sjboeing** [comment]
On https://cds.climate.copernicus.eu/cdsapp#!/yourrequests, there is a "delete selected" button, which can also be applied before a dataset is retrieved. Let me know if that doesn't work for testing.
