### ISSUE TITLE
Path of trajectory files

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#28]
@leifdenby: lagtraj is currently looking for trajectories in the data directory, rather than in the input_examples directory as far as I can tell (it might be same for forcings). It does work when full file paths are provided, but this is inconvenient for the performance readme document. Would this be easy for you to change?

**Comment by leifdenby** [comment]
Let's talk about this on a call. That is by design yes, but maybe we should change it or it's unclear

**Comment by sjboeing** [comment]
#29 discusses the fix for this
