### ISSUE TITLE
Handle failed download requests

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#38]
ERA5 requests sometimes fail, but it is possible to simply resubmit the request. Currently I am deleting the data requests yaml file when this happens, but obviously this is not an ideal solution.

**Comment by sjboeing** [comment]
I think there is an issue as well if the file is deleted on the ECMWF site between when the download request is placed and when the actual download takes place (apologies, should have copied the error, will do so when this occurs again).

**Comment by leifdenby** [comment]
Suggested solution:

Delete the entry in the `data_requests.yaml` and create new request, and inform user of this. Also post message to user suggesting they can delete `data_requests.yaml` without any loss of data
