### ISSUE TITLE
Optimising interpolation algorithms

### ISSUE THREAD

**Issue by leifdenby** [EUREC4A-UK/lagtraj#6]
@sjboeing just commented that:

> Just looking at a post on cython versus numba and pythran. Looks tempting to try pythran or numba https://flothesof.github.io/optimizing-python-code-numpy-cython-pythran-numba.html

I does look like numba and pythran might be a be easier to write and understand, are those your feelings too @sjboeing ?

**Comment by sjboeing** [comment]
Hi @leifdenby. Yes, that is what I think as well. Numba seems more widely used, is jit (so avoids a setup step when getting the software, although that may be needed in any case), but requires llvmlite. Pythran does not seem to be jit, but it may be possible to inspect the C++ it generates and it is faster in the example. It does not need llvmlite and can be installed via pip, but seems to have more dependencies overall. The code for both seems similar though, so we could experiment.

**Comment by sjboeing** [comment]
Hej @leifdenby. Slowly making progress on the interpolation, it is exciting to see the island chain pop up as nans. Numba and pythran have very similar performance with numba being slightly faster so far. I would be tempted to use numba for now, especially if we manage to limit the overhead on compiling: it likely has a bigger user community, was easier to install on my laptop (pythran needed setting up a .pythranrc file), and I think we can make it an optional dependency (the njit decorator can be defined to do nothing if numba has not been set up). It also means that at least as far as interpolation is concerned, there is no "setup" procedure required for the code. So far it is stand-alone code, I will work on bringing it into the git repository over the next few days.

[t_on_height_levels.nc.zip](https://github.com/EUREC4A-UK/lagtraj/files/4666342/t_on_height_levels.nc.zip)

**Comment by leifdenby** [comment]
Should we close this now @sjboeing? I think what you've implemented achieves what we were hoping for here, no? ⭐

**Comment by sjboeing** [comment]
Yes, think is now good!
