### ISSUE TITLE
Rename formats

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#71]
Rename HIGHTUNE to DEPHY, and RACMO to KPT (KNMI parametrisation testbed) for clarity?

**Comment by leifdenby** [comment]
Sounds good to me

**Comment by sjboeing** [comment]
Will do this once the HIGHTUNE (to be renamed DEPHY) input is fully implemented.

**Comment by sjboeing** [comment]
Will close this now #75 has been merged
