### ISSUE TITLE
Cleanup before v0.1.0

### ISSUE THREAD

**Issue by leifdenby** [EUREC4A-UK/lagtraj#82]
I think that we should:

- rename https://github.com/EUREC4A-UK/lagtraj/blob/master/input_examples/domains/eurec4a_circle_eul.yaml -> `eurec4a_circle.yaml`

- delete https://github.com/EUREC4A-UK/lagtraj/blob/master/lagtraj/utils/settings.py

- delete https://github.com/EUREC4A-UK/lagtraj/blob/master/lagtraj/utils/parsers.py

- move content in https://github.com/EUREC4A-UK/lagtraj/blob/master/lagtraj/utils/distance.py into https://github.com/EUREC4A-UK/lagtraj/blob/master/lagtraj/utils/geometry.py

- delete https://github.com/EUREC4A-UK/lagtraj/blob/master/lagtraj/utils/dephy.py

Does that sound ok to you @sjboeing?

**Comment by sjboeing** [comment]
Sound good!
