### ISSUE TITLE
Consistency checks before version 0.1.0

### ISSUE THREAD

**Issue by sjboeing** [EUREC4A-UK/lagtraj#93]
Make sure examples/python files etc are consistent.
** Change: lagtraj.forcing.create → lagtraj.forcings.create in wiki where needed
** Check examples consistency (domain needed, dates in file name vs dates of datetime_origin)
** Check how to use paths to refer to files which exist only in the data directory (if desired). Running with the full path generates the files in a file path which is longer than desired.

**Comment by sjboeing** [comment]
Also todo: go through the commands in the readme.

**Comment by leifdenby** [comment]
All example and README we fixed with https://github.com/EUREC4A-UK/lagtraj/pull/143 🥳
